USE CustomerAnalytics;
GO

-- Tabla recursiva escalable para agregar ciudad, estado en el futuro.
CREATE TABLE GEOGRAFIA (
    GEOGRAFIA_ID INT IDENTITY(1,1) PRIMARY KEY,
    GEO_NOMBRE VARCHAR(50) NOT NULL,
    GEOGRAFIA_PADRE_ID INT NULL,
    FOREIGN KEY (GEOGRAFIA_PADRE_ID) REFERENCES GEOGRAFIA(GEOGRAFIA_ID)
);

-- Tabla para registrar los generos
CREATE TABLE GENERO (
    GENERO_ID INT IDENTITY(1,1) PRIMARY KEY,
    GEN_NOMBRE VARCHAR(15) NOT NULL
);

-- Tabla para registrar todos los productos que ofrece el banco
CREATE TABLE PRODUCTO (
    PRODUCTO_ID INT IDENTITY(1,1) PRIMARY KEY,
    PROD_NOMBRE VARCHAR(100) NOT NULL
)


-- Tabla para registrar todos los clientes que tiene el banco IDEAL
CREATE TABLE CLIENTE (
    CLIENTE_ID INT IDENTITY(1,1) PRIMARY KEY,
    GENERO_ID INT NOT NULL,
    GEOGRAFIA_ID INT NOT NULL,
    FECHA_NACIMIENTO DATE NULL,
    FECHA_DE_REGISTRO DATE NOT NULL,
    FECHA_ABANDONO DATE NULL,
    ABANDONO BIT,
    MIEMBRO_ACTIVO BIT,

    CONSTRAINT FK_CLIENTE_GENERO 
        FOREIGN KEY (GENERO_ID) REFERENCES GENERO(GENERO_ID),

    CONSTRAINT FK_CLIENTE_GEOGRAFIA 
        FOREIGN KEY (GEOGRAFIA_ID) REFERENCES GEOGRAFIA(GEOGRAFIA_ID)
);


-- Tabla que registra todos los productos que tiene un cliente IDEAL
CREATE TABLE PRODUCTO_CLIENTE (
    PRODUCTO_CLIENTE_ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    CLIENTE_ID INT NOT NULL,
    PRODUCTO_ID INT NOT NULL,
    FECHA_INICIO_SERVICIO DATE NOT NULL,
    FECHA_FIN_SERVICIO DATE,
    MOTIVO_FIN_SERVICIO CHAR(250),
    SALARIO DECIMAL(18,2),
    BALANCE DECIMAL(18,2),
    PUNTUACION_CREDITICIA INT,

    CONSTRAINT FK_FACT_CLIENTE 
        FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(CLIENTE_ID),

    CONSTRAINT FK_FACT_PRODUCTO 
        FOREIGN KEY (PRODUCTO_ID) REFERENCES PRODUCTO(PRODUCTO_ID),
);

DROP TABLE PRODUCTO_CLIENTE;
DROP TABLE CLIENTE;

-- Tabla para registrar todos los clientes que tiene el banco y resolver este ejercicio
CREATE TABLE CLIENTE (
    CLIENTE_ID BIGINT NOT NULL PRIMARY KEY, -- customer_id
    RECOR_CREDITICIO INT, -- credit_score
    GEOGRAFIA_ID INT NOT NULL, -- country
    GENERO_ID INT NOT NULL, -- gender
    FECHA_NACIMIENTO DATE NULL, -- age: setear dia 1 mes uno ya que solo se sabe el año
    FECHA_DE_REGISTRO DATE NOT NULL, -- tenure: setear dia 1 mes 1 ya que solo se sabe los años de antiguedad
    BALANCE DECIMAL(18,2), -- balance
    PRODUCTOS INT, -- products_number
    TARJETA_DE_CREDITO BIT, -- credit_card
    MIEMBRO_ACTIVO BIT, -- active_member
    SALARIO DECIMAL(18,2), -- estimated_salary
    ABANDONO BIT, -- churn
    FECHA_ABANDONO DATE, -- como no existe columna en dbo.CustomerChurn sera null 
    MOTIVO_FIN_SERVICIO CHAR(250), -- como no existe columna en dbo.CustomerChurn sera null 

    CONSTRAINT FK_CLIENTE_GENERO 
        FOREIGN KEY (GENERO_ID) REFERENCES GENERO(GENERO_ID),

    CONSTRAINT FK_CLIENTE_GEOGRAFIA 
        FOREIGN KEY (GEOGRAFIA_ID) REFERENCES GEOGRAFIA(GEOGRAFIA_ID)
);

-- PROCEDIMIENTOS PARA MIGRAR DATOS DE LA TABLA ORIGINAL A LAS TABLAS COPO DE NIEVE

-- Migrar datos a la tabla geografia
SELECT * FROM GEOGRAFIA;
INSERT INTO GEOGRAFIA (GEO_NOMBRE)
SELECT country FROM dbo.CustomerChurn GROUP BY country;

-- Migrar datos a la tabla genero
SELECT * FROM GENERO;
INSERT INTO GENERO (GEN_NOMBRE)
SELECT gender FROM dbo.CustomerChurn GROUP BY gender;


-- Migrar datos a la tabla clientes
INSERT INTO CLIENTE (
    CLIENTE_ID,
    RECOR_CREDITICIO,
    GEOGRAFIA_ID,
    GENERO_ID,
    FECHA_NACIMIENTO,
    FECHA_DE_REGISTRO,
    BALANCE,
    PRODUCTOS,
    TARJETA_DE_CREDITO,
    MIEMBRO_ACTIVO,
    SALARIO,
    ABANDONO,
    FECHA_ABANDONO,
    MOTIVO_FIN_SERVICIO
)
SELECT
    c.customer_id,
    c.credit_score,
    geo.GEOGRAFIA_ID,
    g.GENERO_ID,
    DATEFROMPARTS(YEAR(GETDATE()) - c.age, 1, 1) AS FECHA_NACIMIENTO,
    DATEFROMPARTS(YEAR(GETDATE()) - c.tenure, 1, 1) AS FECHA_DE_REGISTRO,
    c.balance,
    c.products_number,
    c.credit_card,
    c.active_member,
    c.estimated_salary,
    c.churn,
    NULL AS FECHA_ABANDONO,
    NULL AS MOTIVO_FIN_SERVICIO
FROM dbo.CustomerChurn c
INNER JOIN GEOGRAFIA geo ON geo.GEO_NOMBRE = c.country
INNER JOIN GENERO g ON g.GEN_NOMBRE = c.gender;

SELECT * FROM CLIENTE;

-- Indices necesarios

CREATE INDEX IX_CLIENTE_GENERO ON CLIENTE (GENERO_ID);
CREATE INDEX IX_CLIENTE_GEOGRAFIA ON CLIENTE (GEOGRAFIA_ID);

CREATE INDEX IX_CLIENTE_MIEMBRO_ACTIVO ON CLIENTE (MIEMBRO_ACTIVO);
CREATE INDEX IX_CLIENTE_ABANDONO ON CLIENTE (ABANDONO);

-- Vistas Clientes Activos
CREATE VIEW VW_CLIENTES_ACTIVOS AS
SELECT 
    c.CLIENTE_ID,
    g.GEN_NOMBRE AS Genero,
    geo.GEO_NOMBRE AS Pais,
    c.FECHA_NACIMIENTO,
    c.FECHA_DE_REGISTRO,
    c.BALANCE,
    c.PRODUCTOS,
    c.SALARIO
FROM CLIENTE c
INNER JOIN GENERO g ON c.GENERO_ID = g.GENERO_ID
INNER JOIN GEOGRAFIA geo ON c.GEOGRAFIA_ID = geo.GEOGRAFIA_ID
WHERE c.MIEMBRO_ACTIVO = 1 AND c.ABANDONO = 0;


-- Vista clientes que abandonaron el banco
CREATE VIEW VW_CLIENTES_CHURN AS
SELECT 
    c.CLIENTE_ID,
    g.GEN_NOMBRE AS Genero,
    geo.GEO_NOMBRE AS Pais,
    c.FECHA_ABANDONO,
    c.MOTIVO_FIN_SERVICIO
FROM CLIENTE c
INNER JOIN GENERO g ON c.GENERO_ID = g.GENERO_ID
INNER JOIN GEOGRAFIA geo ON c.GEOGRAFIA_ID = geo.GEOGRAFIA_ID
WHERE c.ABANDONO = 1;

